force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Login_Session__c/Login_Session__c.object-meta.xml
<CustomObject>
    <label>Login Session</label>
    <nameField>
        <displayFormat>LS-{0000}</displayFormat>
        <label>Login Session Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LoginSession</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Login_Session__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>LoginSession</relationshipLabel>
    <relationshipName>LoginSession</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Login_Session__c/fields/Logged_In__c.field-meta.xml
<CustomField>
    <fullName>Logged_In__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Logged In?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Login_Session__c/fields/Session_Time__c.field-meta.xml
<CustomField>
    <fullName>Session_Time__c</fullName>
    <label>Session Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/sessionBatchClass.cls
global class sessionBatchClass implements Database.Batchable<sObject>
{
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        String query = 'SELECT Account__r.Phone,Id,Logged_In__c,Session_Time__c,Token__c FROM Login_Session__c where Logged_In__c=True';
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Login_Session__c> scope)
    {   
        system.debug('>>>>>>>>>>>>Scope>>>>>>>>>>' +scope);
        for(Login_Session__c a : scope){
            if(a.Session_Time__c == system.now()){
                String salt = String.valueOf(Crypto.getRandomInteger());
                String key = string.valueOf(a.Account__r.Phone)+string.valueOf(system.now());
                Blob data = crypto.generateMac('HmacSHA256',Blob.valueOf(salt), Blob.valueOf(key));
                string token= EncodingUtil.convertToHex(data).toUpperCase();                
                a.Logged_In__c=False;
                a.Token__c = token;  
            }
        }
        update scope;
        system.debug('>>>>>>>>>>>>>scope1>>>>>>' +scope);
    }  
    global void finish(Database.BatchableContext BC)
    {
    }
}