force-app/main/default/objects/Opportunity/fields/Account_type__c.field-meta.xml
<CustomField>
    <fullName>Account_type__c</fullName>
    <label>Account type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Parent_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Parent_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/cloneOpportunityApexController.cls
public class cloneOpportunityApexController {
    public Opportunity opp{get;set;}
    public List<Opportunity> oppList;
    public String parentopp;
    
    public cloneOpportunityApexController(ApexPages.StandardController controller){
        
        parentopp = ApexPages.currentPage().getParameters().get('Id');
        oppList = [SELECT id,name,Amount,Account_type__c,AccountId,CloseDate,StageName 
                   FROM Opportunity
                   WHERE id=:parentOpp];
    }
    
    public PageReference cloneOpp(){
        opp = new Opportunity();
        for( Opportunity oppt:oppList){
            opp.AccountId = oppt.AccountId;
            opp.Account_type__c = oppt.Account_type__c;
            opp.Amount = oppt.Amount;
            opp.Name = oppt.Name;
            opp.StageName = oppt.StageName;
            opp.CloseDate = oppt.CloseDate;
            opp.Parent_Opportunity__c = oppt.id;
        }
        insert opp;
        PageReference parentPage = new PageReference('/' + opp.Id);
        parentPage.setRedirect(true);
        return parentPage;
    } 
    
    
}