force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Line_Item__c/Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Line_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Line Item</relationshipLabel>
    <relationshipName>Order_Line_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <formula>Product__r.Price__c  *  Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Order Line Item</relationshipLabel>
    <relationshipName>Order_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <label>Unit Price</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Litre</fullName>
            </value>
            <value>
                <fullName>Kg</fullName>
            </value>
            <value>
                <fullName>Kit</fullName>
            </value>
            <value>
                <fullName>Packet</fullName>
            </value>
            <value>
                <fullName>Gram</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/orderProductEntryExtension.cls
public with sharing class orderProductEntryExtension {


    public set<id> pid= new set<id>(); 
    public String searchString {get;set;}
    public String searchstring2 {get;set;} 
    public Product__c[] allProducts {get;set;}
    public Order_Line_Item__c[] shoppingCart {get;set;}
    public String toUnselect {get; set;}
    public string state {get;set;}
    private Order_Line_Item__c [] forDeletion = new Order_Line_Item__c []{};
    public string toselect{get;set;}
    public map<Id,Product__c> MapOrder{get;set;}
    
    public orderProductEntryExtension() {
    
    MapOrder = new  map<Id,Product__c >();
    shoppingCart = [select Id,Quantity__c,Product__c,Price__c,Order__c,Product__r.name,Product__r.Unit_Price__c from  Order_Line_Item__c where Order__c='a0Y6F00000KF7a9'];
       
       for(Order_Line_Item__c oli:shoppingCart ){
       
       pid.add(oli.Product__c);
       
       
       }
       allProducts = [select Id,Name,Product_Name__c,Price__c,Product_Description__c,Unit_Price__c from  Product__c where id not IN :pid];
       for(Product__c p:allProducts)
       {
       MapOrder.put(p.Id,p);
       }
        }
    
    public PageReference removeFromShoppingCart(){
    
        // This function runs when a user hits "remove" on an item in the "Selected Products" section
    
        
    List<Order_Line_Item__c> oLst = [Select Id from Order_Line_Item__c where id=:toUnselect];
    delete oLst;
       
        
     PageReference pageRef = new PageReference('/apex/createorderpage');
            return pageRef;
    }
    
    
        public pagereference addlineitem()
        {     
        Order_Line_Item__c ol = new Order_Line_Item__c();
        ol.Order__c='a0Y6F00000KF7a9';
        ol.Quantity__c=1;
        ol.Product__c=toselect;              
            insert ol;
            PageReference pageRef = new PageReference('/apex/createorderpage');
            return pageRef;

            
        }   
    
    }