force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Order</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account_order__c.field-meta.xml
<CustomField>
    <fullName>Account_order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Account)</relationshipLabel>
    <relationshipName>Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Date__c</fullName>
    <label>Order Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/Order_Line_Item__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Order Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Line_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Order Line Item</relationshipLabel>
    <relationshipName>Order_Line_Item</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <formula>Product__r.Price__c  *  Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Line_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product__c</referenceTo>
    <relationshipLabel>Order Line Item</relationshipLabel>
    <relationshipName>Order_Line_Item</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        <label>Product</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <label>Unit Price</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Litre</fullName>
            </value>
            <value>
                <fullName>Kg</fullName>
            </value>
            <value>
                <fullName>Kit</fullName>
            </value>
            <value>
                <fullName>Packet</fullName>
            </value>
            <value>
                <fullName>Gram</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/orderProductEntryExtension2.cls
/*

edited by : Saifullah Saifi 22/08/2017
*/
public with sharing class orderProductEntryExtension2 {

    

    public List<Order_Line_Item__c > orderList {get;set;}
    public List<Order_Line_Item__c > newOrderList {get;set;}
    public set<id> pid= new set<id>(); 
    public Product__c[] allProducts {get;set;}
    public Account accnt {get;set;}
    public Order_Line_Item__c[] shoppingCart {get;set;}
    public String toUnselect {get; set;}
    public string state {get;set;}
    private Order_Line_Item__c [] forDeletion = new Order_Line_Item__c []{};
    public string toselect{get;set;}
    public map<Id,Product__c> allproductsMap{get;set;}
    public id accid;
    public string ProdName{get; set;}
    public integer count;
    public order__c ord;
    
    public orderProductEntryExtension2() {
        orderList = new List<Order_Line_Item__c >();
        newOrderList = new List<Order_Line_Item__c >();
        allproductsMap = new map<Id,Product__c>(); 
        
        accid = ApexPages.currentPage().getParameters().get('accid');
        orderline(accid);
        allProducts = new List<Product__c>();
        allProducts = [Select Id,Name,Product_Name__c,Price__c,Product_Description__c,Unit_Price__c From Product__c];
        accnt = [Select id,Type,Name From Account WHERE Id =: accid LIMIT 1];
        system.debug('accnt-->'+accnt);
        for(Product__C pro:allProducts)
            allproductsMap.put(pro.id,pro);
          count=0;
        ord= new order__c();
    }
    
    public PageReference removeFromShoppingCart(){
        List<Order_Line_Item__c> oLst = [Select Id from Order_Line_Item__c where id=:toUnselect];
        delete oLst;
        orderline(accid);
        return null;
    }
    
    
    public pagereference addlineitem()
    {     
       List<order__c> ordList=[select id from order__c where Account_order__c=:accid];
      
      if(count==0){      
      ord.Name ='Order-'+accid;
      ord.Account_order__c=accid;
      ord.Order_Date__c= system.today();
      insert ord;
          system.debug('ord'+ord);
                       count++;      
      }

          Order_Line_Item__c ol = new Order_Line_Item__c();
        ol.Order__c=ord.id;
        ol.Quantity__c=1;
            ol.Product__c=toselect;
        Product__c temPro =  allproductsMap.get(toselect);
        system.debug(temPro.name);
        if(temPro != Null)
            //ol.Product__r.name = temPro.name;
       
        system.debug(ol.Product__r.name);
        newOrderList.add(ol);            
         insert ol;
         system.debug(orderList);
        orderline(accid);
         //orderList.add(ol);
        //PageReference pageRef = new PageReference('/apex/createorderpage');
        return null;

        
    }   
     public void orderline(string accid){
     
         orderlist =[select Id,Quantity__c,Product__c,Price__c,Order__c,Product__r.name,Product__r.Unit_Price__c from  Order_Line_Item__c where order__r.Account_order__c=:accid];
        
     
     }
      public PageReference cancel() {
         PageReference acctPage = new PageReference('/'+accid);
            acctPage.setRedirect(true);
        return acctPage; 
        
    }


    public PageReference save() {
         PageReference acctPage = new PageReference('/'+orderlist[0].Order__c);
            acctPage.setRedirect(true);
        return acctPage;
    }
    public PageReference search() {
        if(ProdName!=''){
            string search= '%'+ProdName+'%';
            allProducts =[Select Id,Name,Product_Name__c,Price__c,Product_Description__c,Unit_Price__c From Product__c where Name LIKE:search];
            }
        else{
        allProducts = [Select Id,Name,Product_Name__c,Price__c,Product_Description__c,Unit_Price__c From Product__c];      
        }
        return null;
    }


   
    

}